### ISSUE TITLE
Tracker is not logging in with Riot account

### ISSUE THREAD

**Issue by GiovaniBiagi** [VALTracker/DesktopClient#10]
I am trying to login with my RIOT account to have access to my personal data but the tracker does not sign in.

Am I doing something wrong or is Tracker not working?

**Comment by SpiritLetsPlays** [comment]
Hey, sorry this took such a long time to answer to. We have recently identified an issue with the login process, which will be fixed in an update that will be released today. Please download that version, and try to log in again. 
If it works: Great!
If it doesn't work, please join our [Discord Server](https://discord.gg/aJfQ4yHysG) for further support.
